disabled_rules:
  - type_name
  - trailing_whitespace
  - identifier_name
  - line_length
  - function_body_length
  - control_statement
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods